# Generated by Django 4.2.4 on 2023-08-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_stock_reciever_donation_reciever_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='hospital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
