# Generated by Django 4.2.4 on 2023-08-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_request_is_fullfilled_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='is_fullfilled',
            new_name='is_fulfilled',
        ),
    ]
