# Generated by Django 4.2.4 on 2023-08-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_request_patient_age_request_patient_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='blood_group',
            new_name='group',
        ),
    ]
