# Generated by Django 4.2.4 on 2023-08-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_blood_group_request_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='hospital',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
