# Generated by Django 4.2.4 on 2023-08-20 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_request_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recieved_stocks', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recieves', to='app.profile'),
        ),
    ]
