# Generated by Django 4.2.4 on 2023-08-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_stock_reciever_alter_donation_reciever'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='reciever',
            new_name='receiver',
        ),
        migrations.AddField(
            model_name='stock',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Expired', 'Expired'), ('Used', 'Used')], default='Available', max_length=10),
        ),
    ]
