# Generated by Django 4.2.4 on 2023-08-20 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_reciever_stock_receiver_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='donation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock', to='app.donation'),
        ),
    ]
