# Generated by Django 4.2.4 on 2023-10-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_stock_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='app.request'),
        ),
        migrations.AddField(
            model_name='request',
            name='blood_type',
            field=models.CharField(choices=[('Whole Blood', 'Whole Blood'), ('Platelets', 'Platelets'), ('Plasma', 'Plasma')], default='Whole Blood', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='emergency',
            field=models.BooleanField(default=False),
        ),
    ]
