# Generated by Django 4.2.4 on 2023-10-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_donation_request_request_blood_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
