# Generated by Django 4.2.4 on 2023-10-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_stock_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date_time',
        ),
        migrations.AddField(
            model_name='request',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
